Repository Lakshya-GG/JavaScript-Games, pull requests merged in 2023-10, with the labels that each got.

#2 Update: Documentation for the repository.
  README.md
Labels: hacktoberfest-accepted

#7 An update required
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#8 Update README.md
  Flappy Bird/README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#9 Adding the Information.md for the repository
  INSTRUCTIONS.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#10 Card Matching Game Project
  card-matching-game/README.md
  card-matching-game/package-lock.json
  card-matching-game/package.json
  card-matching-game/public/favicon.ico
  card-matching-game/public/images/F-1.png
  card-matching-game/public/images/F-2.png
  card-matching-game/public/images/G-1.png
  card-matching-game/public/images/G-2.png
  card-matching-game/public/images/W-1.png
  card-matching-game/public/images/W-2.png
  card-matching-game/public/images/cover.png
  card-matching-game/public/images/preview.png
  card-matching-game/public/index.html
  card-matching-game/public/logo192.png
  card-matching-game/public/logo512.png
  card-matching-game/public/manifest.json
  card-matching-game/public/robots.txt
  card-matching-game/src/App.css
  card-matching-game/src/App.js
  card-matching-game/src/components/Card.css
  card-matching-game/src/components/Card.js
  card-matching-game/src/index.css
  card-matching-game/src/index.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
